name = "HttpClient"
uuid = "a8bcf8b1-64b8-41f7-8d00-5e694f9aa795"
authors = ["Samarin Aleksei <liotbiu1@gmail.com> and contributors"]
version = "1.4.0-DEV"

[deps]
LibCURL2 = "a9341e5c-07f0-4893-8fea-80ee6f4ebcc7"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
